#This file will have the variable keys from the git technology to provide
#the respective and correct initialization of the environment (qa/hml/prd)

#SSO Datasource
spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://localhost:5432/iam
spring.datasource.username: postgres
spring.datasource.password: secret

spring.datasource.hikari.maximum-pool-size: 5
spring.jpa.properties.hibernate.default_schema: public
spring.jpa.hibernate.ddl-auto: update
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.show-sql: false

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR

jwt.secret: ${JWT_SECRET}
jwt.secret-refresh-token: ${REFRESH_TOKEN_SECRET}

#LDAP
spring:
  application:
    name: "sso"
  main:
    allow-bean-definition-overriding: true
  ldap:
    base: dc=sso,dc=security,dc=com,dc=br
    urls: ldap://localhost:8389
    username: uid=user
    password: password
    embedded:
      base-dn: dc=sso,dc=security,dc=com,dc=br
      credential:
        username: uid=user
        password: password
      ldif: classpath:schema.ldif
      port: 8389
      validation:
        enabled: false